[package]
name = "virtual-voting"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types" }
zero = { path = "../zero" }

[dev-dependencies]
blockdag = { path = "../blockdag" }
config = { path = "../config" }
