[package]
name = "protocol-plugins"
version = "0.1.0"
edition = "2024"

[dependencies]
blockdag = { path = "../blockdag" }
indexmap = "2.7.1"
protocol = { path = "../protocol" }
common = { path = "../common" }
virtual-voting = { path = "../virtual-voting" }
zero = { path = "../zero" }