[package]
name = "consensus-feed"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
consensus = { path = "../consensus" }
protocol = { path = "../../protocol" }
virtual-voting = { path = "../virtual-voting" }