[package]
name = "consensus-feed"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
consensus = { path = "../consensus" }
protocol = { path = "../../protocol" }
tracing = "0.1.41"
virtual-voting = { path = "../virtual-voting" }
async-trait = "0.1.88"