[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
virtual-voting = { path = "../protocol-plugins/virtual-voting" }
zero = { path = "../zero" }

[dev-dependencies]
block-storage = { path = "../protocol-plugins/block-storage"}
config = { path = "../config" }
protocol-plugins = { path = "../protocol-plugins-old" }