[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
blockdag = { path = "../blockdag" }
common = { path = "../common" }
virtual-voting = { path = "../virtual-voting" }
zero = { path = "../zero" }
thiserror = "2.0.12"

[dev-dependencies]
config = { path = "../config" }
protocol-plugins = { path = "../protocol-plugins" }