[package]
name = "block-dag"
version = "0.1.0"
edition = "2024"

[dependencies]
block-storage = { path = "../block-storage"}
common = { path = "../../common" }
indexmap = "2.9.0"
protocol = { path = "../../protocol" }
tracing = "0.1.41"
async-trait = "0.1.88"