[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
blockdag = { path = "../blockdag" }
protocol = { path = "../protocol" }
protocol-plugins = { path = "../protocol-plugins" }
common = { path = "../common" }
virtual-voting = { path = "../virtual-voting" }