[package]
name = "virtual-voting"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../common" }
zero = { path = "../../zero" }
thiserror = "2.0.12"

[dev-dependencies]
block-dag = { path = "../block-dag" }
config = { path = "../../config" }
