[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
blockdag = { path = "../blockdag" }
utils = { path = "../utils" }
virtual-voting = { path = "../virtual-voting" }
zero = { path = "../zero" }
