[package]
name = "consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
blockdag = { path = "../blockdag" }
indexmap = "2.7.1"
types = { path = "../types" }
utils = { path = "../utils" }
virtual-voting = { path = "../virtual-voting" }
zero = { path = "../zero" }
