[package]
name = "blockdag"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.7.1"
types = { path = "../types" }
virtual-voting = { path = "../virtual-voting" }
thiserror = "2.0.12"

[dev-dependencies]
config = { path = "../config" }
